name: Check

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4
        id: changes
        with:
          filters: |
            nix:
              - "**/*.nix"
              - "flake.lock"
      - uses: DeterminateSystems/determinate-nix-action@021c8a1bd3570eb21f5c20a054812b0c4d9ca614 # v3
      - name: Check formatting
        run: nix fmt -- --check
      - name: Check flake evaluation
        if: steps.changes.outputs.nix == 'true'
        run: |
          nix eval .#nixosConfigurations.nixstation.config.system.build.toplevel.drvPath --no-write-lock-file
          nix eval .#nixosConfigurations.wslstation.config.system.build.toplevel.drvPath --no-write-lock-file
          nix eval .#nixosConfigurations.homestation.config.system.build.toplevel.drvPath --no-write-lock-file
          nix eval .#darwinConfigurations.macstation.system --apply 's: s.drvPath' --no-write-lock-file
